nodes:
- type: file
  name: 'index.jsx'
  templateDir: js
  templateFile: 'main.js'
- type: file
  name: 'main.scss'
  templateDir: 'styles'
  templateFile: 'main.scss'
- type: file
  name: 'theme.scss'
  templateDir: 'styles'
  templateFile: 'theme.scss'
- type: dir
  name: api
- type: dir
  name: assets
- type: dir
  name: config
- type: dir
  name: constants
- type: dir
  name: lib
- type: dir
  name: modules
- type: dir
  name: resources
- type: dir
  name: services
- type: dir
  name: 'ui.primitives'
- type: dir
  name: 'ui.components'
- type: dir
  name: 'ui.widgets'
- type: dir
  name: 'ui.pageViews'
- type: dir
  name: 'ui.partials'
- type: dir
  name: 'ui.templates'
- type: dir
  name: 'ui.decorators'
- type: dir
  name: utils
- type: dir
  name: vendor