nodes:
- type: file
  name: 'main.js'
  templateDir: app
  templateFile: 'main.js'
- type: file
  name: 'routes.js'
  templateDir: 'js'
  templateFile: 'routes.js'
- type: file
  name: 'main.scss'
  templateDir: 'styles'
  templateFile: 'main.scss'
- type: dir
  name: api
- type: dir
  name: assets
- type: dir
  name: config
- type: dir
  name: constants
- type: dir
  name: helpers
- type: dir
  name: lib
- type: dir
  name: modules
- type: dir
  name: resources
- type: dir
  name: services
- type: dir
  name: store
- type: dir
  name: ui.primitives
- type: dir
  name: ui.components
- type: dir
  name: ui.widgets
- type: dir
  name: 'ui.pages'
- type: dir
  name: 'ui.partials'
- type: dir
  name: 'ui.templates'
- type: dir
  name: utils