nodes:
- type: file
  name: 'webpack.config.js'
  templateDir: 'config'
  templateFile: 'webpackCore.js'
- type: file
  name: 'postcss.config.js'
  templateDir: 'config'
  templateFile: 'postcss.js'
- type: file
  name: 'webpack.config.js'
  templateDir: 'config'
  templateFile: 'webpack.config.js'
- type: file
  name: 'README.md'
  templateDir: 'docs'
  templateFile: 'README.md'
- type: dir
  name: app
- type: dir
  name: libs
